#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: qmake
# autospec version: v21
# autospec commit: e36a856
#
Name     : pyotherside
Version  : 1.6.2
Release  : 25
URL      : https://github.com/thp/pyotherside/archive/1.6.2/pyotherside-1.6.2.tar.gz
Source0  : https://github.com/thp/pyotherside/archive/1.6.2/pyotherside-1.6.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : ISC
Requires: pyotherside-lib = %{version}-%{release}
Requires: pyotherside-license = %{version}-%{release}
BuildRequires : buildreq-qmake
BuildRequires : pkgconfig(Qt6OpenGL)
BuildRequires : pkgconfig(Qt6Qml)
BuildRequires : pkgconfig(Qt6Quick)
BuildRequires : pkgconfig(Qt6Svg)
BuildRequires : pkgconfig(Qt6Test)
BuildRequires : python3-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
PyOtherSide: Python 3 QML Plugin for Qt 5 and Qt 6
==================================================

%package lib
Summary: lib components for the pyotherside package.
Group: Libraries
Requires: pyotherside-license = %{version}-%{release}

%description lib
lib components for the pyotherside package.


%package license
Summary: license components for the pyotherside package.
Group: Default

%description license
license components for the pyotherside package.


%prep
%setup -q -n pyotherside-1.6.2
cd %{_builddir}/pyotherside-1.6.2
pushd ..
cp -a pyotherside-1.6.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export QMAKE_CFLAGS="$CFLAGS"
export QMAKE_CXXFLAGS="$CXXFLAGS"
export QMAKE_LFLAGS="$LDFLAGS"
export QMAKE_LIBDIR=/usr/lib64
export QMAKE_CFLAGS_RELEASE=
export QMAKE_CXXFLAGS_RELEASE=
export PATH=/usr/lib64/qt6/bin:$PATH
qmake6 -config ltcg -config fat-static-lto
test -r config.log && cat config.log
make  %{?_smp_mflags}
pushd ../buildavx2/
qmake6 'QT_CPU_FEATURES.x86_64 += avx avx2 bmi bmi2 f16c fma lzcnt popcnt'\
    QMAKE_CFLAGS+="-march=x86-64-v3 -Wl,-z,x86-64-v3" QMAKE_CXXFLAGS+="-march=x86-64-v3 -Wl,-z,x86-64-v3" \
    QMAKE_LFLAGS+="-march=x86-64-v3" -config ltcg -config fat-static-lto  
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1739816855
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pyotherside
cp %{_builddir}/pyotherside-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pyotherside/fa70524241a62f69cd81be8837e57b77e0ad445c || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/tests/qtquicktests/qtquicktests
/usr/tests/qtquicktests/qtquicktests

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/qt6/qml/io/thp/pyotherside/libpyothersideplugin.so
/usr/lib64/qt6/qml/io/thp/pyotherside/libpyothersideplugin.so
/usr/lib64/qt6/qml/io/thp/pyotherside/pyotherside.qmltypes
/usr/lib64/qt6/qml/io/thp/pyotherside/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pyotherside/fa70524241a62f69cd81be8837e57b77e0ad445c
