#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: qmake
# autospec version: v3
# autospec commit: c1050fe
#
Name     : pyotherside
Version  : 1.6.0
Release  : 23
URL      : https://github.com/thp/pyotherside/archive/1.6.0/pyotherside-1.6.0.tar.gz
Source0  : https://github.com/thp/pyotherside/archive/1.6.0/pyotherside-1.6.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : ISC
Requires: pyotherside-lib = %{version}-%{release}
Requires: pyotherside-license = %{version}-%{release}
BuildRequires : buildreq-qmake
BuildRequires : mesa-dev
BuildRequires : pkgconfig(Qt5OpenGL)
BuildRequires : pkgconfig(Qt5Qml)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(Qt5Test)
BuildRequires : python3-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
PyOtherSide: Python 3 QML Plugin for Qt 5 and Qt 6
==================================================

%package lib
Summary: lib components for the pyotherside package.
Group: Libraries
Requires: pyotherside-license = %{version}-%{release}

%description lib
lib components for the pyotherside package.


%package license
Summary: license components for the pyotherside package.
Group: Default

%description license
license components for the pyotherside package.


%prep
%setup -q -n pyotherside-1.6.0
cd %{_builddir}/pyotherside-1.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%qmake -config ltcg -config fat-static-lto
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1702062706
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pyotherside
cp %{_builddir}/pyotherside-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pyotherside/9b7d1bcb2d2614f294aedf5b47da5bb7c3511754 || :
%make_install

%files
%defattr(-,root,root,-)
/usr/tests/qtquicktests/qtquicktests

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so
/usr/lib64/qt5/qml/io/thp/pyotherside/pyotherside.qmltypes
/usr/lib64/qt5/qml/io/thp/pyotherside/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pyotherside/9b7d1bcb2d2614f294aedf5b47da5bb7c3511754
